### ISSUE TITLE
openSUSE-repos-MicroOS is the default installed on TW

### ISSUE THREAD

**Issue by lkocman** [openSUSE/openSUSE-repos#20]
zypper in openSUSE-repos installs openSUSE-repos-MicroOS on Tumbleweed while it sould be openSUSE-repos-Tumbleweed

**Comment by develop7** [comment]
It does install `openSUSE-repos-Tumbleweed` for me, but `zypper dup` tries to replace it with `openSUSE-repos-MicroOS`

**Comment by lkocman** [comment]
Fixed in last PR by removing obsoletes on Tumbleweed subpackages. Thank you!
