### ISSUE TITLE
NVIDIA repo

### ISSUE THREAD

**Issue by lkocman** [openSUSE/openSUSE-repos#28]
I'd like to add NVIDIA repo under RIS management too, however, since this repo is not on all systems, we might need to think through under which conditions do we enable repo etc.

**Comment by andrii-suse** [comment]
it could be in another package, like `sudo zypper in openSUSE-repos-Leap-NVIDIA` ?

**Comment by sndirsch** [comment]
So this is just the information about how where to find the repo, not the repo itself? I'm fine with adding nvidia repo to this system as well. If this information is put into a RPM, we could install this package by default only on systems with NVIDIA card (hardware supplements).

**Comment by lkocman** [comment]
Yes it's just "management" of the repo file definition.
In this way we can easily manage repos with a simple package update.

**Comment by sndirsch** [comment]
Ok. Then I' m all for that change. :-)

**Comment by milachew** [comment]
I noticed this change and I would like to ask a couple of questions about it, if I may:

1. After acceptance and appropriate work, those users who do not have access to the NVIDIA website (error code 403) will have the opportunity to install/update their drivers (without VPN/proxy)?

2. Is there any approval from NVIDIA for the full implementation of this?

**Comment by lkocman** [comment]
Just to ensure we're on all page, we're still going to use the same set of repositories. The difference here is that user won't have to call z`ypper addrepo --refresh 'https://download.nvidia.com/opensuse/leap/$releasever' NVIDIA`, but instead will use `zypper in openSUSE-repos-NVIDIA` which will result into enablement of the correct repo for given distribution.

We're going to use the same NVIDIA repositories as in https://en.opensuse.org/SDB:NVIDIA_drivers#Zypper
So from the NVIDIA "host and distributor" perspective nothing really changes. So no additional approval needed.

**Comment by lkocman** [comment]
https://en.opensuse.org/SDB:NVIDIA_drivers#openSUSE-repos

**Comment by lkocman** [comment]
There is a last caviat that I'd like to address correctly and that's the automatic gpg key import.

I was initially thinking of sticking --gpg-auto-import-keys somewhere, but that would not be much useful for offline installations. Plus based on the --help serviceadd call does not display autoimport as an option.

How uncool would be shipping the 3rd party (NVIDIA) gpg-pubkey as part of the package?

**Comment by lkocman** [comment]
I did talk to Michael, and as of today we don't have  a solution how to avoid the confirmation of gpg key import. We can ship gpg key as part of package and either copy it to zypper's cache or to the location for rpm. However user will still have to approve the import dialog.
