### ISSUE TITLE
Tumbleweed having issue with noarch pacakges

### ISSUE THREAD

**Issue by pstarliu** [openSUSE/openSUSE-repos#33]
Hi, somehow after install the new repo after saw the announcement from here:[](https://forums.opensuse.org/t/try-out-the-new-cdn-with-opensuse-repos/168082/3).

I am having issues using Zypper with a few packages, and they all seems are noarch packages:
![image](https://github.com/openSUSE/openSUSE-repos/assets/1468741/9a2cd280-760f-4d01-bfa6-071c7d23090e)

EDIT: I jused updated openSUSE-repos_Tumbleweed to the latest version: 'openSUSE-repos-Tumbleweed-20230804.41e41a9-1.1.x86_64', same result.

**Comment by UltherEgo** [comment]
You need to disable the old repositories after installing the new ones and refresh.
Having two repositories enabled generates conflicts.

Old: https://download.opensuse.org/ports/riscv/tumbleweed/repo/oss/noarch/
New: https://cdn.opensuse.org/ports/riscv/tumbleweed/repo/oss/noarch/

**Comment by pstarliu** [comment]
Thanks, that fixed my issue.
