### ISSUE TITLE
Trailing slash on distsub

### ISSUE THREAD

**Issue by rodrigopedra** [openSUSE/openSUSE-repos#48]
For example:

https://github.com/openSUSE/openSUSE-repos/blob/6289e33b0f04d9b82ee23b1b9a84df3024378258/opensuse-tumbleweed-repoindex.xml#L3

This will lead to a double slash upon URI expansion, as seen if you run `zypper lr --uri`

```
53 | openSUSE:repo-non-oss                        | repo--> | Yes     | (r ) Yes  | Yes     | http://cdn.opensuse.org/tumbleweed//repo/non-oss
54 | openSUSE:repo-openh264                       | repo--> | Yes     | (r ) Yes  | Yes     | http://codecs.opensuse.org/openh264/openSUSE_Tumbleweed
55 | openSUSE:repo-oss                            | repo--> | Yes     | (r ) Yes  | Yes     | http://cdn.opensuse.org/tumbleweed//repo/oss
56 | openSUSE:repo-oss-debug                      | repo--> | No      | ----      | ----    | http://cdn.opensuse.org/debug/tumbleweed//repo/oss
57 | openSUSE:repo-oss-source                     | repo--> | No      | ----      | ----    | http://cdn.opensuse.org/source/tumbleweed//repo/oss
58 | openSUSE:update-tumbleweed                   | updat-> | Yes     | (r ) Yes  | Yes     | http://cdn.opensuse.org/update/tumbleweed/
```

Which is not an issue per se, as it usually is ignored. 

But is an issue when trying to install a Yast one-click-install file that needs the same URI for a dependency, as it will try to add another repository with the "same" URI (without the double slash)

One alternative, in case `distsub` needs the trailing slash, is to remove double slashes upon variable expansion

**Comment by lkocman** [comment]
Fixed in #46
