### ISSUE TITLE
Quality Assurance

### ISSUE THREAD

**Issue by lkocman** [openSUSE/openSUSE-repos#54]
We have to prevent following

- [x]  Mixing flavors within our three-distribution-shared-project TW, MicroOS, Slowroll (all consume from openSUSE:Factory) [boo#1224184](https://bugzilla.opensuse.org/show_bug.cgi?id=1224184) candidate for openQA

- [x] Avoid breaking repository urls, which breaks update path. [boo#1224185](https://bugzilla.suse.com/show_bug.cgi?id=1224185) Can be handled in Github CI

[openQA tracker poo#160340](https://progress.opensuse.org/issues/160340) (any help is welcome)

[Discussion on factory](https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/DP3CC5RICD2GJVYBC7OZXEQUBG2Q3G4J/)

**Comment by lkocman** [comment]
Imho a simple github ci, that would parse and substitutes urls and would compare them to expected urls that have all fetchable repomd.xml

As far as flavor combination goes ... that's tricky and should not be part of CI in github, but syhould be tested in openQA

**Comment by andrii-suse** [comment]
I accidentally opened https://github.com/openSUSE/openSUSE-repos/pull/55 , while wanted to test https://github.com/andrii-suse/openSUSE-repos/pull/1

So currently the test files do install zypp-service in a container and then try to install a package.
They should catch url typos at least.

**Comment by lkocman** [comment]
Basic CI is already running https://github.com/openSUSE/openSUSE-repos/actions, it found few issues on Leap-ports anbd Slowroll (Thanks to Bernhard for fixing these instantly),  now we need the openQA part.

**Comment by lkocman** [comment]
Some basic openqa coverage https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19302 (any help is welcome on it)

**Comment by lkocman** [comment]
All merged. Closing many thanks @andrii-suse !
